using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using VirtoCommerce.Platform.Core.Common;
using VirtoCommerce.Punchout.Core.Models;
using VirtoCommerce.Punchout.Core.Services;
using Permissions = VirtoCommerce.Punchout.Core.ModuleConstants.Security.Permissions;

namespace VirtoCommerce.Punchout.Web.Controllers.Api;

[Authorize]
[Route("api/punchout-integrations")]
public class PunchoutIntegrationController(
    IPunchoutIntegrationService crudService,
    IPunchoutIntegrationSearchService searchService)
    : Controller
{
    [HttpPost("search")]
    [Authorize(Permissions.Read)]
    public async Task<ActionResult<PunchoutIntegrationSearchResult>> Search([FromBody] PunchoutIntegrationSearchCriteria criteria)
    {
        // Cloned results: the secret hash is cleared below and must not be cleared in the shared cache.
        var result = await searchService.SearchAsync(criteria);

        foreach (var integration in result.Results)
        {
            HideSecrets(integration);
        }

        return Ok(result);
    }

    [HttpPost]
    [Authorize(Permissions.Create)]
    public Task<ActionResult<PunchoutIntegration>> Create([FromBody] PunchoutIntegration model)
    {
        model.Id = null;
        return Update(model);
    }

    [HttpPut]
    [Authorize(Permissions.Update)]
    public async Task<ActionResult<PunchoutIntegration>> Update([FromBody] PunchoutIntegration model)
    {
        // The hash may only be derived from a shared secret supplied in the same request, never posted directly.
        // An empty hash keeps the one already stored for this integration.
        model.SharedSecretHash = null;

        await crudService.SaveChangesAsync([model]);

        HideSecrets(model);

        return Ok(model);
    }

    [HttpGet("{id}")]
    [Authorize(Permissions.Read)]
    public async Task<ActionResult<PunchoutIntegration>> Get([FromRoute] string id, [FromQuery] string responseGroup = null)
    {
        // Cloned result: the secret hash is cleared below and must not be cleared in the shared cache.
        var model = await crudService.GetByIdAsync(id, responseGroup);

        HideSecrets(model);

        return Ok(model);
    }


    [HttpGet("new")]
    [Authorize(Permissions.Read)]
    public ActionResult<PunchoutIntegration> GetNew()
    {
        var model = AbstractTypeFactory<PunchoutIntegration>.TryCreateInstance();

        model.IsActive = true;
        model.SharedSecret = Guid.NewGuid().ToString("N");

        return Ok(model);
    }

    [HttpDelete]
    [Authorize(Permissions.Delete)]
    [ProducesResponseType(typeof(void), StatusCodes.Status204NoContent)]
    public async Task<ActionResult> Delete([FromQuery] string[] ids)
    {
        await crudService.DeleteAsync(ids);
        return NoContent();
    }

    /// <summary>
    /// The shared secret is shown only once, when it is generated by GetNew.
    /// Neither it nor its hash ever leaves the API afterwards.
    /// </summary>
    private static void HideSecrets(PunchoutIntegration model)
    {
        if (model != null)
        {
            model.SharedSecret = null;
            model.SharedSecretHash = null;
        }
    }
}
