<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <SonarQubeTestProject>false</SonarQubeTestProject>
  </PropertyGroup>
  <ItemGroup>
	<PackageReference Include="VirtoCommerce.ProfileExperienceApiModule.Data" Version="3.1021.0" />
    <PackageReference Include="VirtoCommerce.XCart.Core" Version="3.1038.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\VirtoCommerce.Punchout.Core\VirtoCommerce.Punchout.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Authorization\" />
    <Folder Include="Commands\" />
    <Folder Include="Schemas\" />
  </ItemGroup>
</Project>
