<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <SonarQubeTestProject>false</SonarQubeTestProject>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="VirtoCommerce.XCart.Core" Version="3.1033.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\VirtoCommerce.Punchout.Core\VirtoCommerce.Punchout.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Authorization\" />
    <Folder Include="Queries\" />
  </ItemGroup>
</Project>
